In [6]:
import pandas as pd 
import os 

filepath = os.path.join('..', 'data', 'processed', 'cleaned_train_data_logScaled.csv')

df = pd.read_csv(filepath)

In [7]:
df = df.drop('X18', axis=1)

In [8]:
df

,ID,X1,X2,X3,X4,X5,X6,X7,X8,X10,...,X12,X13,X14,X15,X16,X17,X19,Y,X9_Month,X9_Year
0,256039,3600.0,0,7.37,1,0,1,62004.0,0,5,...,1.945910,0.0,8.615227,19.5,20.0,1,1.81552,0,2,2009
1,176486,12000.0,1,16.49,4,6,1,143000.0,0,1,...,2.708050,1.0,8.667164,75.4,36.0,0,1.00000,0,11,2014
2,392670,8500.0,1,11.49,0,1,1,27000.0,0,3,...,2.564949,0.0,6.109248,2.0,22.0,1,1.81552,1,6,2010
3,46168,3725.0,0,10.99,0,11,0,14916.0,2,1,...,2.708050,0.0,8.788441,23.9,26.0,0,0.00000,0,11,2015
4,313821,28000.0,0,15.41,4,0,0,100000.0,1,1,...,2.484907,1.0,9.769956,53.2,29.0,1,0.00000,1,12,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
316819,149632,24000.0,0,7.90,1,9,0,128000.0,2,2,...,2.564949,0.0,10.237313,24.6,23.0,1,1.81552,0,1,2012
316820,324071,8000.0,0,12.12,0,11,0,35000.0,2,1,...,1.945910,0.0,8.460623,53.1,17.0,1,2.00000,1,6,2013
316821,164619,15000.0,0,18.55,4,9,1,88400.0,2,1,...,2.639057,1.0,9.481436,55.3,23.0,1,2.00000,0,9,2013
316822,183340,10800.0,1,24.99,5,1,2,36000.0,2,1,...,2.197225,2.0,8.854950,96.0,25.0,1,5.00000,0,4,2014
316823,152215,2200.0,0,20.20,4,5,0,16000.0,0,7,...,1.945910,0.0,6.625392,0.6,7.0,1,0.00000,0,11,2013

In [9]:
df.to_csv(filepath)

In [10]:

filepath2 = os.path.join('..', 'data', 'processed', 'cleaned_test_data_logScaled.csv')

df2 = pd.read_csv(filepath2)

In [11]:
df2

,ID,X1,X2,X3,X4,X5,X6,X7,X8,X10,...,X12,X13,X14,X15,X16,X17,X18,X19,X9_Month,X9_Year
0,335599,25000.0,0,5.32,1,0,1,90000.0,0,6,...,2.995732,0.0,10.592426,13.0,40.0,0,0,2.0,4,2016
1,234182,14000.0,0,13.11,0,0,0,85500.0,0,1,...,2.079442,0.0,9.511629,65.0,21.0,1,0,0.0,3,2013
2,335286,7000.0,0,8.39,0,0,1,77000.0,0,6,...,1.609438,1.0,5.849325,10.5,12.0,1,0,5.0,4,2016
3,172447,2500.0,0,15.61,2,11,0,14000.0,2,2,...,1.945910,0.0,8.174139,52.2,9.0,1,0,0.0,11,2013
4,345387,3500.0,0,13.33,2,6,1,83000.0,1,5,...,2.708050,0.0,10.413703,91.8,28.0,0,0,4.0,8,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71601,391186,8400.0,0,8.18,0,1,1,53000.0,0,1,...,2.484907,0.0,9.327679,32.8,22.0,0,0,0.0,6,2015
71602,306219,21000.0,1,16.59,4,0,1,95000.0,1,1,...,2.639057,0.0,8.843038,77.8,21.0,1,0,3.0,4,2014
71603,133782,6500.0,0,10.49,0,4,0,67000.0,2,1,...,3.367296,0.0,9.067624,12.0,50.0,1,0,0.0,12,2014
71604,136738,15000.0,0,22.74,3,0,0,97000.0,1,3,...,2.397895,1.0,10.425045,57.3,25.0,1,0,2.0,12,2016
71605,384732,21125.0,0,14.09,0,2,0,48500.0,2,1,...,2.564949,0.0,9.979847,61.2,20.0,0,0,0.0,12,2012

In [13]:
df2 = df2.drop('X18', axis=1)

In [14]:
df2.to_csv(filepath2)

In [16]:
filepath3 = os.path.join('..', 'data', 'processed', 'cleaned_test_data.csv')

df3 = pd.read_csv(filepath3)

In [17]:
df3 = df3.drop('X18', axis=1)

In [18]:
df3.to_csv(filepath3)

In [21]:
filepath4 = os.path.join('..', 'data', 'processed', 'cleaned_train_data.csv')

df4 = pd.read_csv(filepath4)

In [22]:
df4 = df4.drop('X18', axis=1)

In [23]:
df4.to_csv(filepath4)